---
title: Reticulate Allows R and Python to be Best Friends
author: Priyanka Kar
date: '2020-12-11'
slug: reticulate-allows-r-and-python-to-be-best-friends
categories: []
tags: []
description: ''
---

Different coding languages do not have to exist apart from each other. When we moved on from Rstudio to Jupyter Notebook in class, I thought that I was moving on completely from R to Python. With this, I thought I would have to change my entire frame of mind about how to do any computations using data. However, with Reticulate, I can jump between R and Python and essentially have the two languages talk to one another!

```{R}
library(reticulate)

library(ggplot2)

```

This is a code chunk in R where we opened reticulate.

```{python}
import numpy as np
list=np.array([[1,2],[3,4]])
```

Now we can open this list in R!

```{R}
listr <- solve(py$list)
listr
```

We can even multiply the two variables together!

```{python}
np.dot(list,r.listr).round()
```

This is just the minimum but we can make models in python too from R! Iris is a dataset in R, but we can do an anova model with it in python.

```{R}
fit<-lm(Petal.Width~Species, data=iris)
anova(fit)
```

The fact that we can have R and python communicate with reticulate is really cool! 